# Generated by Django 5.1.1 on 2024-10-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='creatorType',
            field=models.CharField(choices=[('user', 'User'), ('flyright', 'FlyRight')], default='user', max_length=255),
        ),
    ]
