# Generated by Django 5.1.1 on 2024-10-05 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcardset_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcardcategory'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
