# Generated by Django 5.1.1 on 2024-10-05 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_flashcard_category_alter_flashcard_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='creatorType',
            field=models.CharField(choices=[('user', 'User'), ('flyright', 'FlyRight')], default='user', max_length=255),
        ),
        migrations.AddField(
            model_name='flashcardcategory',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcardcategory',
            name='creatorType',
            field=models.CharField(choices=[('user', 'User'), ('flyright', 'FlyRight')], default='user', max_length=255),
        ),
        migrations.AddField(
            model_name='flashcardcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='creatorType',
            field=models.CharField(choices=[('user', 'User'), ('flyright', 'FlyRight')], default='user', max_length=255),
        ),
    ]
