# Generated by Django 5.1.1 on 2024-10-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_flashcard_ai_generated_flashcard_creatortype_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('question', 'set')},
        ),
    ]
