# Generated by Django 5.1.1 on 2024-10-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_alter_flashcard_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='bold_answer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='bold_question',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
