# Generated by Django 5.1.1 on 2024-10-05 03:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_flashcard_bold_answer_flashcard_bold_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashcardset',
            unique_together={('name', 'creatorType'), ('name', 'user')},
        ),
    ]
