# Generated by Django 5.1.1 on 2024-10-03 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('avg_rating', models.FloatField(default=0)),
                ('feedback_count', models.IntegerField(default=0)),
                ('avg_pass_rate', models.FloatField(default=0)),
                ('avg_flight_difficulty', models.FloatField(default=0)),
                ('avg_oral_difficulty', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GougeFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('gouge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=3)),
                ('pass_or_fail', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('flight_difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Hard')], default=2)),
                ('oral_difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Hard')], default=2)),
                ('stress_level', models.IntegerField(default=3)),
                ('unexpected_elements', models.TextField(blank=True, null=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gouge.examinerprofile')),
            ],
        ),
    ]
