# Generated by Django 5.1.1 on 2024-12-29 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('avg_rating', models.FloatField(default=0)),
                ('feedback_count', models.IntegerField(default=0)),
                ('avg_pass_rate', models.FloatField(default=0)),
                ('avg_flight_difficulty', models.FloatField(default=0)),
                ('avg_oral_difficulty', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FlightManeuver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('checkride_types', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OralTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('checkride_types', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Gouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('gouge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=3)),
                ('pass_or_fail', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('flight_difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Hard')], default=2)),
                ('oral_difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Hard')], default=2)),
                ('stress_level', models.IntegerField(default=3)),
                ('unexpected_elements', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=255)),
                ('avionics_type', models.CharField(choices=[('SIX_PACK', 'Six Pack'), ('GLASS', 'Glass Cockpit'), ('HYBRID', 'Hybrid')], default='GLASS', max_length=20)),
                ('flyright_used', models.BooleanField(default=False)),
                ('flight_hours', models.FloatField(default=0.0)),
                ('oral_duration', models.IntegerField(default=0)),
                ('flight_duration', models.IntegerField(default=0)),
                ('checkride_type', models.CharField(choices=[('PPL', 'Private Pilot License'), ('IFR', 'Instrument Flight Rules'), ('CPL', 'Commercial Pilot License'), ('CFI', 'Certified Flight Instructor'), ('CFII', 'Certified Flight Instructor Instrument'), ('MEI', 'Multi-Engine Instructor'), ('CPC', 'Certified Professional Controller'), ('ATP', 'Airline Transport Pilot')], default='PPL', max_length=10)),
                ('examiner_explanation', models.TextField(default='')),
                ('examiner_behavior', models.TextField(default='')),
                ('examiner_professionalism', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], default=3)),
                ('oral_pass', models.BooleanField(default=False)),
                ('oral_difficult_topics', models.JSONField(default=dict)),
                ('flight_pass', models.BooleanField(default=False)),
                ('maneuver_ratings', models.JSONField(default=dict)),
                ('flight_conditions', models.TextField(default='')),
                ('examiner_focus', models.TextField(default='')),
                ('preparation_tips', models.TextField(default='')),
                ('stress_management_tips', models.TextField(default='')),
                ('general_feedback', models.TextField(default='')),
                ('aircraft_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gouge.aircrafttype')),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gouge.examinerprofile')),
                ('flight_maneuvers', models.ManyToManyField(to='gouge.flightmaneuver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oral_topics', models.ManyToManyField(to='gouge.oraltopic')),
            ],
        ),
        migrations.CreateModel(
            name='GougeFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gouge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gouge.gouge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
