# Generated by Django 5.1.1 on 2024-12-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
