# Generated by Django 5.1.1 on 2024-12-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouge', '0002_alter_aircrafttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmaneuver',
            name='checkride_types',
            field=models.CharField(choices=[('PPL', 'Private Pilot License'), ('IFR', 'Instrument Flight Rules'), ('CPL', 'Commercial Pilot License'), ('CFI', 'Certified Flight Instructor'), ('CFII', 'Certified Flight Instructor Instrument'), ('MEI', 'Multi-Engine Instructor'), ('CPC', 'Certified Professional Controller'), ('ATP', 'Airline Transport Pilot')], default='PPL', max_length=10),
        ),
        migrations.AlterField(
            model_name='oraltopic',
            name='checkride_types',
            field=models.CharField(choices=[('PPL', 'Private Pilot License'), ('IFR', 'Instrument Flight Rules'), ('CPL', 'Commercial Pilot License'), ('CFI', 'Certified Flight Instructor'), ('CFII', 'Certified Flight Instructor Instrument'), ('MEI', 'Multi-Engine Instructor'), ('CPC', 'Certified Professional Controller'), ('ATP', 'Airline Transport Pilot')], default='PPL', max_length=10),
        ),
    ]
