# Generated by Django 5.1.1 on 2024-12-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouge', '0003_alter_flightmaneuver_checkride_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('WEATHER', 'Weather Conditions'), ('VISIBILITY', 'Visibility Conditions'), ('WIND', 'Wind Conditions'), ('OTHER', 'Other Conditions')], max_length=50)),
            ],
        ),
    ]
