# Generated by Django 5.1.1 on 2024-12-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouge', '0005_remove_gouge_flight_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcondition',
            name='name',
            field=models.CharField(choices=[('VFR', 'Visual Flight Rules'), ('MVFR', 'Marginal VFR'), ('IFR', 'Instrument Flight Rules'), ('LIFR', 'Low IFR'), ('LIGHT_TURB', 'Light Turbulence'), ('MOD_TURB', 'Moderate Turbulence'), ('SEV_TURB', 'Severe Turbulence'), ('LIGHT_WIND', 'Light Winds (0-10 kts)'), ('MOD_WIND', 'Moderate Winds (10-20 kts)'), ('STRONG_WIND', 'Strong Winds (20+ kts)'), ('CROSSWIND', 'Crosswind Component'), ('WIND_SHEAR', 'Wind Shear'), ('GUSTING', 'Gusting Conditions'), ('CLEAR', 'Clear Skies'), ('SCATTERED', 'Scattered Clouds'), ('BROKEN', 'Broken Clouds'), ('OVERCAST', 'Overcast'), ('LOW_CEILING', 'Low Ceiling'), ('FOG', 'Foggy Conditions'), ('RAIN', 'Rain'), ('SNOW', 'Snow'), ('ICING', 'Icing Conditions'), ('NIGHT', 'Night Conditions'), ('MOUNTAIN', 'Mountain Operations'), ('HIGH_DA', 'High Density Altitude'), ('HOT_TEMP', 'High Temperature'), ('COLD_TEMP', 'Cold Temperature')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gouge',
            name='flight_conditions',
            field=models.ManyToManyField(blank=True, null=True, to='gouge.flightcondition'),
        ),
    ]
