# Generated by Django 5.1.1 on 2024-12-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouge', '0007_remove_gouge_flight_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gouge',
            name='flight_conditions',
        ),
        migrations.AddField(
            model_name='gouge',
            name='flight_conditions',
            field=models.ManyToManyField(blank=True, to='gouge.flightcondition'),
        ),
    ]
